check if the remote ip is the same as we have locally, or else update

diff --git a/duckdns b/duckdns
--- a/duckdns
+++ b/duckdns
@@ -12,19 +12,29 @@ else
     exit 1
 fi
 
-if [ ! -f "$LAST_IP" ]; then
-    if NEW_IP="$(dig +short myip.opendns.com @208.67.222.222)"; then
-        echo "$NEW_IP" > "$LAST_IP"
-        logger -t duckdns "Initialization succeeded, domain: $DOMAIN.duckdns.org, IP: $NEW_IP"
-    else
-        logger -t duckdns "Unable to detect the public IP address"
-        exit 1
-    fi
+
+DOMAIN_DNS="example.com"
+
+# Resolve IP using nslookup
+CURRENT_DOMAIN_DNS_IP=$(nslookup "$DOMAIN_DNS" | awk '/^Address: / { print $2 }' | tail -n 1)
+
+if [ "$CURRENT_DOMAIN_DNS_IP" == "$LAST_IP" ]; then
+  logger -t duckdns "IP is still the same, not updating"
+else
+  if [ ! -f "$LAST_IP" ]; then
+      if NEW_IP="$(dig +short myip.opendns.com @208.67.222.222)"; then
+          echo "$NEW_IP" > "$LAST_IP"
+          logger -t duckdns "Initialization succeeded, domain: $DOMAIN.duckdns.org, IP: $NEW_IP"
+      else
+          logger -t duckdns "Unable to detect the public IP address"
+          exit 1
+      fi
+  fi
 fi
 
 while true; do
     if CURRENT_IP="$(dig +short myip.opendns.com @208.67.222.222)"; then
-        if [ "$CURRENT_IP" != "$(< $LAST_IP)" ]; then
+        if [ "$CURRENT_IP" != "$CURRENT_DOMAIN_DNS_IP" ]; then
             if RESULT="$(curl -s "https://www.duckdns.org/update?domains=$DOMAIN&token=$TOKEN&ip=$CURRENT_IP")"; then
                 if [ "$RESULT" = "OK" ]; then
                     echo "$CURRENT_IP" > "$LAST_IP"
@@ -35,6 +45,8 @@ while true; do
             else
                 logger -t duckdns "Update failed, unable to connect"
             fi
+        else
+          logger -t duckdns "$CURRENT_IP = $CURRENT_DOMAIN_DNS_IP, not updating"
         fi
     else
         logger -t duckdns "Unable to detect the public IP address"
